services:
  - type: web
    name: realtime-chat-app
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free
